import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,dirname} from 'node:path';
import {loadFixture} from '../load.mjs';
import {normalize,normalizeRelationship,buildAnchorIndex,joinAnchor} from '../normalize.mjs';
import {contentHash} from '../identity.mjs';
const hash=x=>contentHash(Buffer.from(x));
async function specimen() {
  const root=await mkdtemp(join(tmpdir(),'admission-'));
  const files={}; const put=(path,value)=>{files[path]=typeof value==='string'?value:JSON.stringify(value);};
  const source='export function go() { return 1; }\n';
  const document={sourceSetId:'main',language:'javascript',path:'src/go.js'};
  const native={id:'native',version:'1',executableHash:hash('native 1'),kind:'native',languages:['javascript'],positionEncoding:'utf8'};
  const semantic={...native,id:'semantic',kind:'semantic',executableHash:hash('semantic 1')};
  const captures=[];
  for(const [ref,kind,file,text] of [['native','executable','captures/native.bin','native 1'],['semantic','executable','captures/semantic.bin','semantic 1'],['tool','toolchain','captures/tool.txt','tool'],['config','config','captures/config.txt','config'],['deps','dependency','captures/deps.txt','deps'],['fact','semanticArtifact','captures/fact.json',JSON.stringify({formatVersion:1,producerId:'semantic',facts:[]})]]) {
    put(file,text); captures.push({ref,kind,file,hash:hash(text)});
  }
  put('captures/native.json',{formatVersion:1,producerId:'native',declarations:[],calls:[],controls:[],references:[]});
  put('src/go.js',source);
  put('src/go.js.annotations.json',{formatVersion:1,document,revisionId:'r1',scenarios:[],facts:[]});
  put('expected/answers.json',{formatVersion:1,answers:[]}); put('expected/dispositions.json',{formatVersion:1,assertions:[],callableValueNegatives:[]});
  put('expected/anchors.json',{formatVersion:1,cases:[]});
  const fixture={formatVersion:1,profile:'example',language:'javascript',sourceSets:[{id:'main',rootId:'root',languages:['javascript'],dependencies:[]}],producers:[native,semantic],revisions:[{id:'r1',sourceSetId:'main',documents:[{key:document,revisionId:'r1',sourceFile:'src/go.js'}],toolchainHash:hash('tool'),configHash:hash('config'),dependencyHash:hash('deps')}],comparison:{sourceSetId:'main',revisionId:'r1',producers:[native,semantic]},coverageIntents:[],nativeArtifact:'captures/native.json',semanticArtifacts:['captures/fact.json'],annotationFiles:['src/go.js.annotations.json'],answersFile:'expected/answers.json',dispositionsFile:'expected/dispositions.json',anchorCasesFile:'expected/anchors.json',captures};
  async function flush(){put('fixture.json',fixture); for(const [path,value] of Object.entries(files)){await mkdir(dirname(join(root,path)),{recursive:true});await writeFile(join(root,path),value);}}
  await flush();return {root,files,fixture,document,source,flush,cleanup:()=>rm(root,{recursive:true,force:true})};
}
const span=(start,end)=>({encoding:'utf8',start,end});
const row=(s,ref='decl')=>({ref,nativeId:'opaque',document:s.document,revisionId:'r1',parentRef:null,kind:'function',name:'go',range:span(0,31),nameRange:span(16,18),header:{kind:'function',name:'go',modifiers:[],typeParameters:[],parameters:[],resultType:null,bases:[]},signature:null,witnesses:[{field:'name',witness:{range:span(16,18),text:'go'}}]});
function setNative(s,rows){s.files['captures/native.json']=JSON.stringify({formatVersion:1,producerId:'native',declarations:rows,calls:[],controls:[],references:[]});}
test('NORMALIZE.SOURCE identity and native diagnostic independence',async t=>{const s=await specimen();t.after(s.cleanup);setNative(s,[row(s)]);await s.flush();let result=normalize(await loadFixture(s.root));assert.equal(result.records.declarations.length,1);assert.deepEqual(result.records.declarations[0].nameRange,{start:16,end:18});const first=result.records.declarations[0].syntaxId;setNative(s,[{...row(s),nativeId:'changed'}]);await s.flush();result=normalize(await loadFixture(s.root));assert.equal(result.records.declarations[0].syntaxId,first);assert.equal(result.identityMap.get('decl'),first);});
test('NORMALIZE.DUPLICATE owner/kind/range rejected',async t=>{const s=await specimen();t.after(s.cleanup);setNative(s,[row(s),{...row(s,'other'),nativeId:null}]);await s.flush();const loaded=await loadFixture(s.root);assert.throws(()=>normalize(loaded),/IDENTITY.ORDINAL/);});

test('NORMALIZE.OCCURRENCE source-derived call/reference ordinals and exact tuple joins',async t=>{const s=await specimen();t.after(s.cleanup);const native={formatVersion:1,producerId:'native',declarations:[row(s)],calls:[{ref:'call',nativeId:'ignored',document:s.document,revisionId:'r1',ownerRef:'decl',range:span(16,20),calleeRange:span(16,18),spelling:'go',regionRefs:[],witnesses:[]}],controls:[],references:[{ref:'reference',nativeId:null,document:s.document,revisionId:'r1',ownerRef:'decl',range:span(16,18),spelling:'go',witnesses:[]}]};s.files['captures/native.json']=JSON.stringify(native);await s.flush();const loaded=await loadFixture(s.root);const result=normalize(loaded);assert.equal(result.records.calls.length,1);assert.match(result.records.calls[0].id,/^occ:v1:/);assert.equal(result.records.references.length,0);assert.equal(result.identityMap.has('reference'),true);});
test('NORMALIZE.CALLEE does not guess a range from the separate spelling witness',async t=>{const s=await specimen();t.after(s.cleanup);const call={ref:'call',nativeId:null,document:s.document,revisionId:'r1',ownerRef:'decl',range:span(16,20),calleeRange:null,spelling:'go',regionRefs:[],witnesses:[{field:'spelling',witness:{range:span(16,18),text:'go'}}]};const native={formatVersion:1,producerId:'native',declarations:[row(s)],calls:[call],controls:[],references:[]};s.files['captures/native.json']=JSON.stringify(native);await s.flush();const loaded=await loadFixture(s.root);assert.equal(normalize(loaded).records.calls[0].calleeRange,null);call.witnesses=[];s.files['captures/native.json']=JSON.stringify(native);await s.flush();assert.throws(()=>normalize({...loaded,native}),/WITNESS.MISSING/);});

test('NORMALIZE.REFERENCE_JOIN non-exact diagnostics do not fabricate reference records',async t=>{const s=await specimen();t.after(s.cleanup);const sourceHash=hash(s.source);const basis={producerId:'semantic',producerVersion:'1',producerHash:s.fixture.producers[1].executableHash,artifactHash:null,language:'javascript',sourceSetId:'main',revisionId:'r1',sourceManifestHash:null,toolchainHash:s.fixture.revisions[0].toolchainHash,configHash:s.fixture.revisions[0].configHash,dependencyHash:s.fixture.revisions[0].dependencyHash,lookupDependencies:[]};const anchor={document:s.document,revisionId:'r1',contentHash:sourceHash,kind:'reference',range:span(16,18),ownerRef:'decl'};const fact={kind:'reference',ref:'ref1',anchor,record:{site:'use',roles:['read'],resolution:'unresolved',declaredTarget:null,candidates:[],provenanceId:'proof1'}};const native={formatVersion:1,producerId:'native',declarations:[row(s)],calls:[],controls:[],references:[]};s.files['captures/native.json']=JSON.stringify(native);const raw=JSON.stringify({formatVersion:1,producerId:'semantic',facts:[fact]});s.files['captures/fact.json']=raw;s.fixture.captures.find(x=>x.ref==='fact').hash=hash(raw);await s.flush();let loaded=await loadFixture(s.root);basis.artifactHash=hash(raw);basis.sourceManifestHash=loaded.sourceManifestHash(loaded.selected);const provenance={id:'proof1',producerId:'semantic',document:s.document,revisionId:'r1',contentHash:sourceHash,evidenceKind:'semanticReference',basis,freshness:'fresh'};s.files['src/go.js.annotations.json']=JSON.stringify({formatVersion:1,document:s.document,revisionId:'r1',scenarios:[],facts:[{kind:'provenance',ref:'provenance1',record:provenance},fact]});await s.flush();loaded=await loadFixture(s.root);const output=normalize(loaded).records;assert.equal(output.references.length,0);assert.equal(output.referenceJoinDiagnostics.length,1);assert.deepEqual(output.referenceJoinDiagnostics[0].join.candidateIds,[]);assert.equal(output.referenceJoinDiagnostics[0].join.status,'unmatched');native.references.push({ref:'native-reference',nativeId:null,document:s.document,revisionId:'r1',ownerRef:'decl',range:span(16,18),spelling:'go',witnesses:[]});s.files['captures/native.json']=JSON.stringify(native);await s.flush();const exact=normalize(await loadFixture(s.root)).records;assert.equal(exact.referenceJoinDiagnostics.length,0);assert.equal(exact.references.length,1);assert.equal(exact.references[0].spelling,'go');assert.equal(exact.references[0].resolution,'unresolved');});

test('NORMALIZE.RELATIONSHIP maps all authored kinds with directed internal source',()=>{const document={sourceSetId:'main',language:'javascript',path:'src/go.js'};const declarations=new Map([['child',{document,revisionId:'r1'}],['parent',{document,revisionId:'r1'}]]);const ids=new Map([['child','sid:v1:'+'a'.repeat(32)],['parent','sid:v1:'+'b'.repeat(32)]]);for(const kind of ['extends','implements','overrides']){const fact={kind:'typeRelationship',ref:kind,relationshipKind:kind,source:{kind:'internal',declarationRef:'child',revisionId:'r1'},target:{kind:'internal',declarationRef:'parent',revisionId:'r1'},provenanceRef:'independent-proof'};const output=normalizeRelationship(fact,ids,declarations);assert.equal(output.kind,kind);assert.equal(output.source.syntaxId,ids.get('child'));assert.equal(output.target.syntaxId,ids.get('parent'));assert.equal(output.provenanceId,'independent-proof');}});

test('NORMALIZE.JOIN counts distinct measured candidate IDs and exact tuple',async t=>{const s=await specimen();t.after(s.cleanup);setNative(s,[row(s)]);await s.flush();const loaded=await loadFixture(s.root);const anchor={document:s.document,revisionId:'r1',contentHash:contentHash(Buffer.from(s.source)),kind:'reference',range:span(16,18),ownerRef:'decl'};const measured={document:s.document,revisionId:'r1',contentHash:anchor.contentHash,kind:'reference',range:{start:16,end:18}};const one={ref:'one',id:'occ:v1:'+'1'.repeat(32),anchor:measured,ownerRef:'decl'},two={...one,ref:'two',id:'occ:v1:'+'2'.repeat(32)};let join=joinAnchor(anchor,buildAnchorIndex([one,one]),loaded);assert.equal(join.status,'exact');join=joinAnchor(anchor,buildAnchorIndex([one,two]),loaded);assert.equal(join.status,'ambiguous');assert.equal(join.candidateIds.length,2);join=joinAnchor({...anchor,range:span(17,18)},buildAnchorIndex([one]),loaded);assert.equal(join.status,'unmatched');});
